### PR TITLE
Translation fixes in installer and user language selector

### PR DESCRIPTION
**Pull request by forelo**

### CODE REVIEW

**Comment by vanpouckesven** [comment]
Can you explain the code 

`Configuration::reset();`

In the QuickLanguageComponent?

**Comment by forelo** [comment]
The language selector only works when the cache is cleared.
This function clears the config cache and forces a storage reload.

**Comment by ScaraMcDuck** [comment]
Clearing the configuration cache is no longer done via the deprecated static reset method in the deprecated class "Configuration. Please use the clearData method of the general configuration consulter service to do this.

**Comment by vanpouckesven** [comment]
Some additional information: The ConfigurationConsulter service can be retrieved using our dependency injection system. In each component you have the ability to use the method $this->getService with the ID of the service as an argument. 

To retrieve the ConfigurationConsulter service in another component you can simply do this:

`$this->getService('chamilo.configuration.service.configuration_consulter')`

**Comment by forelo** [comment]
The service is now implemented in the commit

**Pull request merged**
